name: bmed360

channels:
  - simpleitk
  - conda-forge
  - anaconda
#  - pytorch

dependencies:
  - python==3.8
  - jupyter
  - ipython
  - ipykernel
  - jupyterlab
  - matplotlib
  - pip
  - git
  - gdown
  - ipywidgets
  - itkwidgets
  - pyvista
  - numpy
  - scipy
  - sympy
  - pandas
  - openpyxl
  - seaborn
  - SimpleITK
  - scikit-image
  - scikit-learn
  - scikit-plot
  - eli5
  - pdpbox
  - dipy
  - imageio
  - dcm2niix
  - tifffile
  - statsmodels
  - nibabel
  - nilearn
#  - pycaret==2.3
  - networkx
#  - pytorch
#  - torchvision


# To remove and reinstall the bmed360 environment (if installation problems):
# conda deactivate
# conda remove env -n bmed360
# conda env update
